# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: purchase_order.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'purchase_order.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14purchase_order.proto\x12\x13\x63om.unla.stockearte\x1a\x1fgoogle/protobuf/timestamp.proto\"\x86\x02\n\rPurchaseOrder\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x30\n\x06orders\x18\x02 \x03(\x0b\x32 .com.unla.stockearte.OrderDetail\x12\x0e\n\x06\x65stado\x18\x03 \x01(\t\x12\x15\n\robservaciones\x18\x04 \x01(\t\x12\x16\n\x0eorden_despacho\x18\x05 \x01(\t\x12\x32\n\x0e\x66\x65\x63haSolicitud\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x32\n\x0e\x66\x65\x63haRecepcion\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08idTienda\x18\x08 \x01(\x05\"M\n\x0bOrderDetail\x12\x0e\n\x06\x63odigo\x18\x01 \x01(\t\x12\r\n\x05\x63olor\x18\x02 \x01(\t\x12\r\n\x05talle\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61ntidad\x18\x04 \x01(\x05\".\n\x1b\x43reatePurchaseOrderResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\",\n\x19\x45\x64itPurchaseOrderResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\".\n\x1b\x44\x65letePurchaseOrderResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"(\n\x1a\x44\x65letePurchaseOrderRequest\x12\n\n\x02id\x18\x01 \x01(\x05\")\n\x1bGetPurchaseOrderByIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"Z\n\x1cGetPurchaseOrderByIdResponse\x12:\n\x0epurchaseOrders\x18\x01 \x03(\x0b\x32\".com.unla.stockearte.PurchaseOrder2\xe5\x03\n\x14PurchaseOrderService\x12k\n\x13\x43reatePurchaseOrder\x12\".com.unla.stockearte.PurchaseOrder\x1a\x30.com.unla.stockearte.CreatePurchaseOrderResponse\x12g\n\x11\x45\x64itPurchaseOrder\x12\".com.unla.stockearte.PurchaseOrder\x1a..com.unla.stockearte.EditPurchaseOrderResponse\x12x\n\x13\x44\x65letePurchaseOrder\x12/.com.unla.stockearte.DeletePurchaseOrderRequest\x1a\x30.com.unla.stockearte.DeletePurchaseOrderResponse\x12}\n\x16ListPurchaseOrdersById\x12\x30.com.unla.stockearte.GetPurchaseOrderByIdRequest\x1a\x31.com.unla.stockearte.GetPurchaseOrderByIdResponseB2\n\x13\x63om.unla.stockearteB\x19PurchaseOrderServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'purchase_order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.unla.stockearteB\031PurchaseOrderServiceProtoP\001'
  _globals['_PURCHASEORDER']._serialized_start=79
  _globals['_PURCHASEORDER']._serialized_end=341
  _globals['_ORDERDETAIL']._serialized_start=343
  _globals['_ORDERDETAIL']._serialized_end=420
  _globals['_CREATEPURCHASEORDERRESPONSE']._serialized_start=422
  _globals['_CREATEPURCHASEORDERRESPONSE']._serialized_end=468
  _globals['_EDITPURCHASEORDERRESPONSE']._serialized_start=470
  _globals['_EDITPURCHASEORDERRESPONSE']._serialized_end=514
  _globals['_DELETEPURCHASEORDERRESPONSE']._serialized_start=516
  _globals['_DELETEPURCHASEORDERRESPONSE']._serialized_end=562
  _globals['_DELETEPURCHASEORDERREQUEST']._serialized_start=564
  _globals['_DELETEPURCHASEORDERREQUEST']._serialized_end=604
  _globals['_GETPURCHASEORDERBYIDREQUEST']._serialized_start=606
  _globals['_GETPURCHASEORDERBYIDREQUEST']._serialized_end=647
  _globals['_GETPURCHASEORDERBYIDRESPONSE']._serialized_start=649
  _globals['_GETPURCHASEORDERBYIDRESPONSE']._serialized_end=739
  _globals['_PURCHASEORDERSERVICE']._serialized_start=742
  _globals['_PURCHASEORDERSERVICE']._serialized_end=1227
# @@protoc_insertion_point(module_scope)
