# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import purchase_order_pb2 as purchase__order__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in purchase_order_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PurchaseOrderServiceStub(object):
    """Servicio para manejar PurchaseOrders
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePurchaseOrder = channel.unary_unary(
                '/com.unla.stockearte.PurchaseOrderService/CreatePurchaseOrder',
                request_serializer=purchase__order__pb2.PurchaseOrder.SerializeToString,
                response_deserializer=purchase__order__pb2.CreatePurchaseOrderResponse.FromString,
                _registered_method=True)
        self.EditPurchaseOrder = channel.unary_unary(
                '/com.unla.stockearte.PurchaseOrderService/EditPurchaseOrder',
                request_serializer=purchase__order__pb2.PurchaseOrder.SerializeToString,
                response_deserializer=purchase__order__pb2.EditPurchaseOrderResponse.FromString,
                _registered_method=True)
        self.DeletePurchaseOrder = channel.unary_unary(
                '/com.unla.stockearte.PurchaseOrderService/DeletePurchaseOrder',
                request_serializer=purchase__order__pb2.DeletePurchaseOrderRequest.SerializeToString,
                response_deserializer=purchase__order__pb2.DeletePurchaseOrderResponse.FromString,
                _registered_method=True)
        self.ListPurchaseOrdersById = channel.unary_unary(
                '/com.unla.stockearte.PurchaseOrderService/ListPurchaseOrdersById',
                request_serializer=purchase__order__pb2.GetPurchaseOrderByIdRequest.SerializeToString,
                response_deserializer=purchase__order__pb2.GetPurchaseOrderByIdResponse.FromString,
                _registered_method=True)


class PurchaseOrderServiceServicer(object):
    """Servicio para manejar PurchaseOrders
    """

    def CreatePurchaseOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditPurchaseOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePurchaseOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPurchaseOrdersById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PurchaseOrderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePurchaseOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePurchaseOrder,
                    request_deserializer=purchase__order__pb2.PurchaseOrder.FromString,
                    response_serializer=purchase__order__pb2.CreatePurchaseOrderResponse.SerializeToString,
            ),
            'EditPurchaseOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.EditPurchaseOrder,
                    request_deserializer=purchase__order__pb2.PurchaseOrder.FromString,
                    response_serializer=purchase__order__pb2.EditPurchaseOrderResponse.SerializeToString,
            ),
            'DeletePurchaseOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePurchaseOrder,
                    request_deserializer=purchase__order__pb2.DeletePurchaseOrderRequest.FromString,
                    response_serializer=purchase__order__pb2.DeletePurchaseOrderResponse.SerializeToString,
            ),
            'ListPurchaseOrdersById': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPurchaseOrdersById,
                    request_deserializer=purchase__order__pb2.GetPurchaseOrderByIdRequest.FromString,
                    response_serializer=purchase__order__pb2.GetPurchaseOrderByIdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.unla.stockearte.PurchaseOrderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.unla.stockearte.PurchaseOrderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PurchaseOrderService(object):
    """Servicio para manejar PurchaseOrders
    """

    @staticmethod
    def CreatePurchaseOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.unla.stockearte.PurchaseOrderService/CreatePurchaseOrder',
            purchase__order__pb2.PurchaseOrder.SerializeToString,
            purchase__order__pb2.CreatePurchaseOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditPurchaseOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.unla.stockearte.PurchaseOrderService/EditPurchaseOrder',
            purchase__order__pb2.PurchaseOrder.SerializeToString,
            purchase__order__pb2.EditPurchaseOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePurchaseOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.unla.stockearte.PurchaseOrderService/DeletePurchaseOrder',
            purchase__order__pb2.DeletePurchaseOrderRequest.SerializeToString,
            purchase__order__pb2.DeletePurchaseOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPurchaseOrdersById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.unla.stockearte.PurchaseOrderService/ListPurchaseOrdersById',
            purchase__order__pb2.GetPurchaseOrderByIdRequest.SerializeToString,
            purchase__order__pb2.GetPurchaseOrderByIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
