# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stock.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'stock.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstock.proto\x12\x13\x63om.unla.stockearte\"J\n\x12\x43reateStockRequest\x12\x0f\n\x07storeId\x18\x01 \x01(\x05\x12\x11\n\tproductId\x18\x02 \x01(\x05\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"T\n\x10\x45\x64itStockRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07storeId\x18\x02 \x01(\x05\x12\x11\n\tproductId\x18\x03 \x01(\x05\x12\x10\n\x08quantity\x18\x04 \x01(\x05\"\x12\n\x10GetStocksRequest\"P\n\x0cStockSummary\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07storeId\x18\x02 \x01(\x05\x12\x11\n\tproductId\x18\x03 \x01(\x05\x12\x10\n\x08quantity\x18\x04 \x01(\x05\"F\n\x11GetStocksResponse\x12\x31\n\x06stocks\x18\x01 \x03(\x0b\x32!.com.unla.stockearte.StockSummary\" \n\rStockResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1d\n\x0fGetStockRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"D\n\x10GetStockResponse\x12\x30\n\x05stock\x18\x01 \x01(\x0b\x32!.com.unla.stockearte.StockSummary2\xf7\x02\n\x0cStockService\x12Z\n\x0b\x43reateStock\x12\'.com.unla.stockearte.CreateStockRequest\x1a\".com.unla.stockearte.StockResponse\x12V\n\tEditStock\x12%.com.unla.stockearte.EditStockRequest\x1a\".com.unla.stockearte.StockResponse\x12Z\n\tGetStocks\x12%.com.unla.stockearte.GetStocksRequest\x1a&.com.unla.stockearte.GetStocksResponse\x12W\n\x08GetStock\x12$.com.unla.stockearte.GetStockRequest\x1a%.com.unla.stockearte.GetStockResponseB*\n\x13\x63om.unla.stockearteB\x11StockServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stock_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.unla.stockearteB\021StockServiceProtoP\001'
  _globals['_CREATESTOCKREQUEST']._serialized_start=36
  _globals['_CREATESTOCKREQUEST']._serialized_end=110
  _globals['_EDITSTOCKREQUEST']._serialized_start=112
  _globals['_EDITSTOCKREQUEST']._serialized_end=196
  _globals['_GETSTOCKSREQUEST']._serialized_start=198
  _globals['_GETSTOCKSREQUEST']._serialized_end=216
  _globals['_STOCKSUMMARY']._serialized_start=218
  _globals['_STOCKSUMMARY']._serialized_end=298
  _globals['_GETSTOCKSRESPONSE']._serialized_start=300
  _globals['_GETSTOCKSRESPONSE']._serialized_end=370
  _globals['_STOCKRESPONSE']._serialized_start=372
  _globals['_STOCKRESPONSE']._serialized_end=404
  _globals['_GETSTOCKREQUEST']._serialized_start=406
  _globals['_GETSTOCKREQUEST']._serialized_end=435
  _globals['_GETSTOCKRESPONSE']._serialized_start=437
  _globals['_GETSTOCKRESPONSE']._serialized_end=505
  _globals['_STOCKSERVICE']._serialized_start=508
  _globals['_STOCKSERVICE']._serialized_end=883
# @@protoc_insertion_point(module_scope)
